baseURL: "https://arcapol.github.io"
title: "Aiwayi Arca"
theme: Mod
paginate: 5

enableRobotsTXT: true
buildDrafts: true

params:
  env: production
  title: "Aiwayi Arca"
  description: "General Rant"
  author: arcapol
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  comments: false
  ShowShareButtons: false
  ShareButtons: ["twitter"]
  ShowWordCount: true

  assets:
    favicon: "icons8-owl-48.png"
    homeIcon: "icons8-tardis-48.png"
  
  # profileMode:
  #   enabled: false
  #   title: "Aiwayi Arca"
  #   buttons:
  #   - name: Posts
  #     url: posts
  #   - name: tags
  #     url: tags

  # homeInfoParams:
  #   Title: "Hi there \U0001F44B"
  #   Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/arcapolshara"

menu:
  main:
    - identifier: archives
      name: archives
      url: /archives/
      weight: 20
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 10
    - identifier: about
      name: about
      url: /about/
      weight: 30